TestNode: testNode.cpp Node.cpp
	g++ testNode.cpp Node.cpp -o exe
	./exe

TestList: TestList.cpp LinkedList.cpp Node.cpp
	g++ TestList.cpp LinkedList.cpp Node.cpp -o exe
	./exe

Main: main.cpp LinkedList.cpp Node.cpp
	g++ main.cpp LinkedList.cpp Node.cpp -o exe
	./exe

Run: *.cpp
	g++ *.cpp -o exe
	./exe