TestNode: BST_Node.cpp TestNode.cpp
	g++ BST_Node.cpp TestNode.cpp -o exe
	./exe

TestTraversal: BST_Node.cpp BST.cpp TestTraversal.cpp
	g++  BST_Node.cpp BST.cpp TestTraversal.cpp -o exe
	./exe

TestISD: BST_Node.cpp BST.cpp TestISD.cpp	# ISD stands for "Insert, Search, and Delete"
	g++ BST_Node.cpp BST.cpp TestISD.cpp -o exe
	./exe

# TestAll: *.cpp
#	g++ *.cpp -o exe
#	./exe